name: check-project.yml
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          "php-version": '8.4'
      - name: install dependencies
        run: make install
      - name: linter
        run: make lint

  sonarqube:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          "php-version": '8.4'
      - name: install dependencies
        run: make install
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
